mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth.views import LoginView, LogoutView
from django.views.generic import RedirectView

urlpatterns = [
    path("polls/", include("polls.urls")),
    path("admin/", admin.site.urls),
    path('login/', LoginView.as_view(template_name='polls/login.html')),
	path('logout/', LogoutView.as_view(next_page='/')),
    path('', RedirectView.as_view(url='/polls/', permanent=True)),
]

mysite/polls/urls.py
from django.urls import path

from . import views

app_name = "polls"
urlpatterns = [
    # ex: /polls/
    path("", views.index, name="index"),
    # ex: /polls/5/
    path("<int:question_id>/", views.detail, name="detail"),
    # ex: /polls/5/results/
    path("<int:question_id>/results/", views.results, name="results"),
    # ex: /polls/5/vote/
    path("<int:question_id>/vote/", views.vote, name="vote"),
    path('add/', views.add, name='add'),
]

mysite/polls/models.py
import datetime

from django.db import models
from django.utils import timezone


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    votes_yes = models.IntegerField(default=0)
    votes_no = models.IntegerField(default=0)
    def __str__(self):
        return self.question_text

mysite/polls/views.py
import sqlite3
import re

from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.db.models import F
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt

from .models import Question


def index(request):
    list = Question.objects.all()
    context = {"list": list, "user": request.user}
    return render(request, "polls/index.html", context)

def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, "polls/detail.html", {"question": question})


def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, "polls/results.html", {"question": question})


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)

    if request.method == 'POST':
        selected_choice = request.POST.get('choice')

        if selected_choice == 'yes':
            question.votes_yes = F("votes_yes") + 1
            question.save()
        elif selected_choice == 'no':
            question.votes_no = F("votes_no") + 1
            question.save()
        else:
            return render(
                request,
                "polls/detail.html",
                {
                    "question": question,
                    "error_message": "You didn't select a choice.",
                },
            )

    return HttpResponseRedirect(reverse("polls:results", args=(question.id,)))

@csrf_exempt
# A5:2017-Broken Access Control, only admins should be able to add polls
def add(request):
    if request.method == 'POST':
        # A1:2017-Injection https://owasp.org/www-project-top-ten/2017/A1_2017-Injection.html
        # Example malicious question_text: '); DROP TABLE polls_question; --
        question_text = request.POST.get('question_text')
        connection = sqlite3.connect('db.sqlite3')
        cursor = connection.cursor()
        query = f"INSERT INTO polls_question (votes_yes, votes_no, question_text) VALUES (0, 0, '{question_text}');"
        cursor.executescript(query)
        connection.commit()
        connection.close()

        return HttpResponseRedirect("/polls")
    
    context = {"user": request.user}
    return render(request, "polls/add.html", context)

'''
# Fix CSRF flaw by removing @csrf_exempt
# Fix A5:2017-Broken Access Control by adding @login_required
@login_required
def add(request):
    # Fix A5:2017-Broken Access Control by checking superuser
    if not request.user.is_superuser:
        return HttpResponseRedirect("/polls")

    if request.method == 'POST':
        question_text = request.POST.get('question_text')
        
        # Partial fix for A1:2017-Injection by adding server-side validation
        pattern = r'^[A-Za-zA-Z0-9, ]*[?]$'
        if not re.match(pattern, question_text):
            context = {"user": request.user, "error_message": "Only alphanumeric input with question mark allowed."}
            return render(request, "polls/add.html", context)
        
        # Fix A1:2017-Injection by using Django's ORM
        question = Question.objects.create(question_text=question_text)
        question.save()

        return HttpResponseRedirect("/polls")
    
    context = {"user": request.user}
    return render(request, "polls/add.html", context)
'''

mysite/polls/templates/polls/add.html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <title>Add a new question</title>
    </head>


    <body>
      <h1>Add a new question</h1>

      <form action="{% url 'polls:add' %}" method="POST">
        <!-- CSRF flaw, fix by adding csrf_token -->
        <!-- {% csrf_token %} -->

        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        <input type="text" name="question_text" required/>
        <br/>
        <input type="submit" value="Send"/>
      </form>

      {% if user.is_authenticated %}
      <h2>Username: {{user.username}}</h2>
      <form action="/logout/" method="POST">
        {% csrf_token %}
        <input type="submit" value="Logout"/>
      </form>
      {% endif %}
    </body>


    </body>
</html>

mysite/polls/templates/polls/detail.html
<!DOCTYPE html>
<html>
  <head>
    <title>Poll: {{ question.question_text }}</title>
  </head>
  <body>
    <form action="{% url 'polls:vote' question.id %}" method="post">
      {% csrf_token %}
      <fieldset required>
          <legend><h1>{{ question.question_text }}</h1></legend>
          {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

          <input type="radio" name="choice" id="choice-yes" value="yes">
          <label for="choice-yes">Yes</label><br>

          <input type="radio" name="choice" id="choice-no" value="no">
          <label for="choice-no">No</label><br>

      </fieldset>
      <input type="submit" value="Vote">
      </form>
  </body>
</html>

mysite/polls/templates/polls/index.html
<!DOCTYPE html>
<html>
  <head>
    <title>Polls</title>
  </head>
  <body>
    <h1>Polls</h1>
    {% if list %}
        <ul>
        {% for question in list %}
          <!-- A7:2017-Cross-Site Scripting (XSS) https://owasp.org/www-project-top-ten/2017/A7_2017-Cross-Site_Scripting_(XSS).html -->
          <!-- Example malicios question_text: <script>var data = new Object();data.content = document.cookie;alert(document.cookie);</script> -->
          <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text|safe }}</a></li>

          <!-- Fix for A7:2017-Cross-Site Scripting (XSS) -->
          <!-- <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li> -->
        {% endfor %}
        </ul>
    {% else %}
        <p>No polls are available.</p>
    {% endif %}

    {% if user.is_authenticated %}
    <h2>Username: {{user.username}}</h2>
    <form action="/logout/" method="POST">
      {% csrf_token %}
      <input type="submit" value="Logout"/>
    </form>
    {% endif %}
  </body>
</html>

mysite/polls/templates/polls/login.html
<h2>Login</h2>
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Login</button>
</form>

mysite/polls/templates/polls/results.html
<!DOCTYPE html>
<html>
  <head>
    <title>Results: {{ question.question_text }}</title>
  </head>
  <body>
    <h1>{{ question.question_text }}</h1>

    <ul>
      <li>Yes -- {{ question.votes_yes }} vote{{ question.votes_yes|pluralize }}</li>
      <li>No -- {{ question.votes_no }} vote{{ question.votes_no|pluralize }}</li>
    </ul>
    
    <a href="{% url 'polls:detail' question.id %}">Vote again?</a>
  </body>
</html>